fix: content with new line
HazardScout/anchorock-kpa pull request #37
Opened 2024-08-20 17:34 UTC by ymarsal-kpa

2024-08-20 18:15 UTC, schwamman requested changes
Can you update this to use a regular expression? Or change it to `replaceAll`? The `replace` function will only update the first matching value if it's given a string.

2024-08-20 18:15 UTC, schwamman commented on base-integration/src/utilities/helper.ts
> +
```suggestion
    const regex = /\/r|\/n/g
    finalData = finalData.replace(regex, ' ')
```

2024-08-20 18:31 UTC, trevorhibblen commented on base-integration/src/utilities/helper.ts
> +
@schwamman we should prob. keep the original format, that way `\r\n` doesn't create two spaces.
```suggestion
    finalData = finalData.replace(/\r\n/g, ' ')
    finalData = finalData.replace(/\r/g, ' ')
    finalData = finalData.replace(/\n/g, ' ')

```

2024-08-28 15:44 UTC, schwamman approved these changes
✅

2024-08-28 15:45 UTC, merged